// Generated by CoffeeScript 1.9.0
(function() {
  module.exports = {
    NEW: 'new',
    SUB: 'sub',
    AUTO: 'auto',
    IMPLICIT: 'implicit',
    GLOBAL_TIMEOUT: null,
    MAX_REQUEST_IN_TRANSACTION: 1000 * 10,
    TICKER_REPEAT: 1000 * 5
  };

}).call(this);
