// Generated by CoffeeScript 1.9.0
(function() {
  var env, _ref, _ref1, _ref2, _ref3;

  env = process.env;

  module.exports = {
    NEW: 'new',
    SUB: 'sub',
    AUTO: 'auto',
    IMPLICIT: 'implicit',
    LOGLEVEL: (_ref = env.XW_LOGLEVEL) != null ? _ref : 'info',
    GLOBAL_TIMEOUT: (_ref1 = env.XW_GLOBAL_TIMEOUT) != null ? _ref1 : null,
    MAX_REQUEST_IN_TRANSACTION: (_ref2 = env.XW_MAX_REQUEST_IN_TRANSACTION) != null ? _ref2 : 1000 * 10,
    TICKER_REPEAT: (_ref3 = env.XW_TICKER_REPEAT) != null ? _ref3 : 1000 * 5
  };

}).call(this);
