// Generated by CoffeeScript 1.9.0
(function() {
  var Promise, Request, __requestNumber;

  Promise = require('bluebird');

  __requestNumber = 0;

  Request = (function() {
    Request.ask = function(id, name) {
      return (new Request(id, name)).getTransaction();
    };

    Request.client = function(id, name) {
      return Request.ask(id, name).then(function(transaction) {
        var _ref;
        return (_ref = transaction != null ? transaction.client() : void 0) != null ? _ref : null;
      });
    };

    Request.takeClient = function(id, name) {
      return Request.ask(id, name.then)(function(transaction) {
        var _ref;
        return (_ref = transaction != null ? transaction.takeClient() : void 0) != null ? _ref : null;
      });
    };

    function Request(_at_id, _at_name) {
      this.id = _at_id;
      this.name = _at_name;
      __requestNumber += 1;
      if (this.name == null) {
        this.name = "?" + __requestNumber;
      }
    }

    Request.prototype.getTransaction = function() {
      var d, err, self;
      self = this;
      this.deferred = d = Promise.defer();
      Request.logger.debug("ASK " + this.name);
      process.nextTick(function() {
        Request.logger.debug("(ASK UP: " + (self.name.slice(0, 4)) + ")");
        d.progress(self);
        return process.nextTick(function() {
          if (d.promise.isPending()) {
            Request.logger.debug("(ASK UNA: " + (self.name.slice(0, 4)) + ")");
            return Request.handleUnanswered(self);
          }
        });
      });
      err = new Error("cancelled");
      return d.promise["catch"](function(cerr) {
        var _ref;
        Request.logger.error((_ref = cerr.stack) != null ? _ref : cerr);
        err.cancel = cerr;
        throw err;
      });
    };

    Request.prototype.fulfill = function(transaction) {
      var _ref;
      if ((_ref = this.deferred) != null ? _ref.promise.isPending() : void 0) {
        Request.logger.debug("FULFILL " + this.name + " by:", transaction != null ? transaction.name.slice(0, 4) : void 0, '---');
        this.deferred.resolve(transaction);
        return delete this.deferred;
      }
    };

    Request.prototype.reject = function(reason) {
      var _ref;
      if ((_ref = this.deferred) != null ? _ref.promise.isPending() : void 0) {
        this.deferred.reject(reason);
        return delete this.deferred;
      }
    };

    Request.handle = function(transaction, promise, id) {
      var _ref;
      Request.logger.debug("HANDLE BY", (_ref = transaction != null ? transaction.name.slice(0, 4) : void 0) != null ? _ref : '----');
      if ((promise == null) || (promise.progressed == null)) {
        throw new Error("Cannot pass transaction: no promise; got " + promise);
      }
      return promise.progressed(function(request) {
        while (request.value != null) {
          request = request.value;
        }
        if (!(request instanceof Request)) {
          return;
        }
        if ((id == null) || (request.id == null) || request.id === id) {
          request.fulfill(transaction);
          throw {
            name: 'StopProgressPropagation'
          };
        }
        Request.logger.debug("REQ-" + request.name + " doesn't match", transaction.name.slice(0, 4));
      });
    };

    Request.handleUnanswered = function(request) {
      debugger;
      return request.fulfill(null);
    };

    return Request;

  })();

  module.exports = Request;

}).call(this);
