// Generated by CoffeeScript 1.9.0
(function() {
  var AUTO, BASIC_INTERFACE, IMPLICIT, Logger, NEW, Promise, Request, SUB, SUBTRANSACTIONS_INTERFACE, Transaction, WRAP_INTERACE, adapters, findAdapterFeatures, fs, initializer, logger, resolveAdapter, _, _ref;

  Promise = require('bluebird');

  _ = require('lodash');

  _ref = require('./constants'), NEW = _ref.NEW, SUB = _ref.SUB, AUTO = _ref.AUTO, IMPLICIT = _ref.IMPLICIT;

  Transaction = require('./transaction');

  Request = require('./request');

  Logger = require('logger-facade-nodejs');

  fs = require('fs');

  logger = Logger.getLogger('xwrap');

  Request.logger = logger;

  Transaction.logger = logger;

  adapters = {};

  module.exports = initializer = function(_arg) {
    var adapter, adapterName, id, settings, wrap, xtransaction;
    adapter = _arg.adapter, settings = _arg.settings, id = _arg.id, wrap = _arg.wrap;
    adapterName = adapter;
    adapter = void 0;
    if (wrap == null) {
      wrap = true;
    }
    xtransaction = function() {
      var arg, callback, i, name, newTransaction, type, _i, _len, _ref1, _ref2;
      if (typeof arguments[0] === 'object') {
        _ref1 = type, type = _ref1.type, callback = _ref1.callback, name = _ref1.name, id = _ref1.id;
      }
      for (i = _i = 0, _len = arguments.length; _i < _len; i = ++_i) {
        arg = arguments[i];
        if (typeof arg === 'function') {
          callback = arg;
          _ref2 = Array.prototype.slice.call(arguments, 0, i), type = _ref2[0], id = _ref2[1], name = _ref2[2];
          break;
        }
      }
      if (callback == null) {
        new Error('callback must be specified');
      }
      newTransaction = new Transaction({
        callback: callback,
        name: name,
        adapter: adapter,
        id: id
      });
      if (type == null) {
        type = IMPLICIT;
      }
      return newTransaction.start(type);
      return newTransaction;
    };
    adapter = resolveAdapter(adapterName, settings, id);
    adapter.id = id;
    adapter.xtransaction = xtransaction;
    findAdapterFeatures(adapter);
    if ((wrap != null) && adapter.features.xwrap.wrap) {
      adapter.wrap(function(callerName) {
        return Request.client(id, callerName);
      });
    }
    xtransaction.client = function(callerName) {
      return Request.client(id, callerName);
    };
    xtransaction.takeClient = function(callerName) {
      return Request.takeClient(id, callerName);
    };
    xtransaction.disconnect = function() {
      adapter.disconnect();
      return delete adapters[adapter.id];
    };
    xtransaction.NEW = NEW;
    xtransaction.SUB = SUB;
    xtransaction.AUTO = AUTO;
    xtransaction.Transaction = Transaction;
    xtransaction.Request = Request;
    xtransaction.adapter = adapter;
    xtransaction.id = id;
    return xtransaction;
  };

  resolveAdapter = function(name, settings, id) {
    var adapter, adapterClass, adapterMod, e;
    adapter = adapters[id];
    if (adapter != null) {
      return adapter;
    }
    try {
      switch (false) {
        case typeof name !== 'object':
          this.name = name.name;
          return name;
        case !name.match(/^\//):
          adapterClass = require(name);
          break;
        case !(fs.existsSync(__dirname + '/adapters/' + name + '.js') || fs.existsSync(__dirname + '/adapters/' + name + '.coffee') || fs.existsSync(__dirname + '/adapters/' + name + '.litcoffee')):
          adapterMod = require('./adapters/' + name);
          break;
        default:
          adapterMod = require("xwrap-" + name);
      }
      return adapterMod.initialize(settings);
    } catch (_error) {
      e = _error;
      if (e.message.indexOf('Cannot find module') !== -1) {
        throw new Error("XWrap adapter '" + name + "' not found.");
      } else {
        throw e;
      }
    }
  };

  BASIC_INTERFACE = ['getClient', 'enableTransactions', 'disableTransactions', 'openTransaction', 'commitTransaction', 'rollbackTransaction'];

  SUBTRANSACTIONS_INTERFACE = ['openSubTransaction', 'commitSubTransaction', 'rollbackSubTransaction'];

  WRAP_INTERACE = ['wrap'];

  findAdapterFeatures = function(adapter) {
    var api, features, method, methods, missing, xwrapFeatures, _i, _j, _len, _len1, _ref1, _results;
    features = (adapter.features != null ? adapter.features : adapter.features = {});
    xwrapFeatures = (features.xwrap != null ? features.xwrap : features.xwrap = {});
    if (xwrapFeatures.clientMethods == null) {
      xwrapFeatures.clientMethods = ['query'];
    }
    if (xwrapFeatures.clientDataAttributes == null) {
      xwrapFeatures.clientDataAttributes = [];
    }
    _ref1 = ['basic', 'subtransactions', 'wrap'];
    _results = [];
    for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
      api = _ref1[_i];
      if (xwrapFeatures[api] != null) {
        continue;
      }
      methods = (function() {
        switch (api) {
          case 'basic':
            return BASIC_INTERFACE;
          case 'subtransactions':
            return SUBTRANSACTIONS_INTERFACE;
          case 'wrap':
            return WRAP_INTERACE;
        }
      })();
      missing = false;
      for (_j = 0, _len1 = methods.length; _j < _len1; _j++) {
        method = methods[_j];
        if (adapter[method] == null) {
          missing = true;
          break;
        }
      }
      _results.push(xwrapFeatures[api] = !missing);
    }
    return _results;
  };

  initializer.client = function(id, callerName) {
    return new Request.client(id, callerName);
  };

  initializer.takeClient = function(id, callerName) {
    return new Request.takeClient(id, callerName);
  };

  initializer.disconnect = function(id) {
    var _ref1;
    if ((_ref1 = adapters[id]) != null) {
      _ref1.disconnect();
    }
    return delete adapters[id];
  };

  initializer.NEW = NEW;

  initializer.SUB = SUB;

  initializer.AUTO = AUTO;

  initializer.Transaction = Transaction;

  initializer.Request = Request;

  initializer.useLogger = function(logger_) {
    return Request.logger = Transaction.logger = logger = logger_;
  };

}).call(this);
